-- MySQL Script generated by MySQL Workbench
-- Wed Mar  4 22:55:50 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema electiondb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `electiondb` ;

-- -----------------------------------------------------
-- Schema electiondb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `electiondb` DEFAULT CHARACTER SET utf8 ;
USE `electiondb` ;

-- -----------------------------------------------------
-- Table `electiondb`.`accesstime`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`accesstime` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`accesstime` (
  `accessID` INT NOT NULL AUTO_INCREMENT,
  `accessTime` INT NULL DEFAULT NULL,
  `accessName` VARCHAR(150) NULL DEFAULT NULL,
  `accessDate` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`accessID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2485
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`admin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`admin` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`admin` (
  `adminID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `username` VARCHAR(45) NULL DEFAULT NULL,
  `password` VARCHAR(128) NULL DEFAULT NULL,
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`adminID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`party`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`party` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`party` (
  `partyID` INT NOT NULL AUTO_INCREMENT,
  `partyName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`partyID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`positionlevel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`positionlevel` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`positionlevel` (
  `levelID` INT NOT NULL AUTO_INCREMENT,
  `levelName` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`levelID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`position`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`position` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`position` (
  `positionID` INT NOT NULL AUTO_INCREMENT,
  `positionTitle` VARCHAR(45) NULL DEFAULT NULL,
  `level` INT NOT NULL,
  PRIMARY KEY (`positionID`),
  INDEX `fk_position_positionLevel1_idx` (`level` ASC) ,
  CONSTRAINT `fk_position_positionLevel1`
    FOREIGN KEY (`level`)
    REFERENCES `electiondb`.`positionlevel` (`levelID`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`candidate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`candidate` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`candidate` (
  `candidateID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `middlename` VARCHAR(45) NULL DEFAULT NULL,
  `position` INT NOT NULL,
  `party` INT NOT NULL,
  `addedBy` INT NOT NULL,
  PRIMARY KEY (`candidateID`),
  INDEX `fk_candidate_party1_idx` (`party` ASC) ,
  INDEX `fk_candidate_position1_idx` (`position` ASC) ,
  INDEX `fk_candidate_admin1_idx` (`addedBy` ASC) ,
  CONSTRAINT `fk_candidate_admin1`
    FOREIGN KEY (`addedBy`)
    REFERENCES `electiondb`.`admin` (`adminID`),
  CONSTRAINT `fk_candidate_party1`
    FOREIGN KEY (`party`)
    REFERENCES `electiondb`.`party` (`partyID`),
  CONSTRAINT `fk_candidate_position1`
    FOREIGN KEY (`position`)
    REFERENCES `electiondb`.`position` (`positionID`))
ENGINE = InnoDB
AUTO_INCREMENT = 92
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`district` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`district` (
  `districtID` INT NOT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  `districtName` VARCHAR(80) NULL DEFAULT NULL,
  `districtContractAddress` BLOB NULL DEFAULT NULL,
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `deploymentcost` VARCHAR(45) NULL DEFAULT NULL,
  `districtAccountKey` BLOB NULL DEFAULT NULL,
  PRIMARY KEY (`districtID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`ethkey`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`ethkey` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`ethkey` (
  `idethKey` INT NOT NULL AUTO_INCREMENT,
  `key` BLOB NULL DEFAULT NULL,
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `owner` INT NULL DEFAULT NULL,
  PRIMARY KEY (`idethKey`),
  INDEX `fk_owner_ethkey_idx` (`owner` ASC) ,
  CONSTRAINT `fk_owner_ethkey`
    FOREIGN KEY (`owner`)
    REFERENCES `electiondb`.`admin` (`adminID`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`precinct`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`precinct` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`precinct` (
  `precinctID` INT NOT NULL,
  `districtID` INT NOT NULL,
  `precinctName` VARCHAR(500) NULL DEFAULT NULL,
  `address` VARCHAR(500) NULL DEFAULT NULL,
  PRIMARY KEY (`precinctID`),
  INDEX `fk_precinct_district1_idx` (`districtID` ASC) ,
  CONSTRAINT `fk_precinct_district1`
    FOREIGN KEY (`districtID`)
    REFERENCES `electiondb`.`district` (`districtID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`smartcontracts`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`smartcontracts` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`smartcontracts` (
  `contractID` INT NOT NULL AUTO_INCREMENT,
  `contractAddress` BLOB NULL DEFAULT NULL,
  `contractName` VARCHAR(45) NULL DEFAULT NULL,
  `deployedBy` INT NOT NULL,
  `contractABI` LONGTEXT NULL DEFAULT NULL,
  `deployDate` DATETIME NULL DEFAULT NULL,
  `active` TINYINT NULL DEFAULT '0',
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `deploymentcost` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`contractID`),
  INDEX `fk_smartContracts_admin1_idx` (`deployedBy` ASC) ,
  CONSTRAINT `fk_smartContracts_admin1`
    FOREIGN KEY (`deployedBy`)
    REFERENCES `electiondb`.`admin` (`adminID`))
ENGINE = InnoDB
AUTO_INCREMENT = 9
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`voter`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`voter` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`voter` (
  `voterID` INT NOT NULL AUTO_INCREMENT,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `middlename` VARCHAR(45) NULL DEFAULT NULL,
  `addedBy` INT NOT NULL,
  `districtID` INT NOT NULL,
  `precinctID` INT NOT NULL,
  `voterStatus` TINYINT NULL DEFAULT '0',
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  `voterPassword` VARCHAR(128) NULL DEFAULT NULL,
  PRIMARY KEY (`voterID`),
  INDEX `fk_voter_admin1_idx` (`addedBy` ASC) ,
  INDEX `fk_voter_district1_idx` (`districtID` ASC) ,
  INDEX `fk_voter_precinct1_idx1` (`precinctID` ASC) ,
  CONSTRAINT `fk_voter_admin1`
    FOREIGN KEY (`addedBy`)
    REFERENCES `electiondb`.`admin` (`adminID`),
  CONSTRAINT `fk_voter_district1`
    FOREIGN KEY (`districtID`)
    REFERENCES `electiondb`.`district` (`districtID`),
  CONSTRAINT `fk_voter_precinct1`
    FOREIGN KEY (`precinctID`)
    REFERENCES `electiondb`.`precinct` (`precinctID`))
ENGINE = InnoDB
AUTO_INCREMENT = 48
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`vote`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`vote` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`vote` (
  `voteID` INT NOT NULL AUTO_INCREMENT,
  `voterID` INT NULL DEFAULT NULL,
  `presidentVote` VARCHAR(45) NULL DEFAULT NULL,
  `vicePresidentVote` VARCHAR(45) NULL DEFAULT NULL,
  `senatorVote` VARCHAR(200) NULL DEFAULT NULL,
  `datetimevoted` TIMESTAMP NULL DEFAULT NULL,
  `voteString` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`voteID`),
  INDEX `fk_vote_voterID_idx` (`voterID` ASC) ,
  CONSTRAINT `fk_vote_voterID`
    FOREIGN KEY (`voterID`)
    REFERENCES `electiondb`.`voter` (`voterID`))
ENGINE = InnoDB
AUTO_INCREMENT = 44
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`timekeeper`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`timekeeper` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`timekeeper` (
  `timeID` INT NOT NULL AUTO_INCREMENT,
  `transactionTime` INT NULL DEFAULT NULL,
  `gasUsed` INT NULL DEFAULT NULL,
  `voteID` INT NULL DEFAULT NULL,
  PRIMARY KEY (`timeID`),
  INDEX `fk_timekeeper_voteID_idx` (`voteID` ASC) ,
  CONSTRAINT `fk_timekeeper_voteID`
    FOREIGN KEY (`voteID`)
    REFERENCES `electiondb`.`vote` (`voteID`))
ENGINE = InnoDB
AUTO_INCREMENT = 43
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`votearchive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`votearchive` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`votearchive` (
  `archiveID` INT NOT NULL AUTO_INCREMENT,
  `voteID` INT NOT NULL,
  `voterID` INT NULL DEFAULT NULL,
  `presidentVote` VARCHAR(45) NULL DEFAULT NULL,
  `vicePresidentVote` VARCHAR(45) NULL DEFAULT NULL,
  `senatorVote` VARCHAR(45) NULL DEFAULT NULL,
  `datetimevoted` TIMESTAMP NULL DEFAULT NULL,
  `voteString` VARCHAR(100) NULL DEFAULT NULL,
  PRIMARY KEY (`archiveID`),
  INDEX `fk_vote_voterID_idx` (`voterID` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 42
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `electiondb`.`voterarchive`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `electiondb`.`voterarchive` ;

CREATE TABLE IF NOT EXISTS `electiondb`.`voterarchive` (
  `archiveID` INT NOT NULL AUTO_INCREMENT,
  `voterID` INT NOT NULL,
  `firstname` VARCHAR(45) NULL DEFAULT NULL,
  `lastname` VARCHAR(45) NULL DEFAULT NULL,
  `middlename` VARCHAR(45) NULL DEFAULT NULL,
  `addedBy` INT NOT NULL,
  `districtID` INT NOT NULL,
  `precinctID` INT NOT NULL,
  `voterStatus` TINYINT NULL DEFAULT '0',
  `voterPassword` VARCHAR(128) NULL DEFAULT NULL,
  `salt` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`archiveID`),
  INDEX `fk_voter_admin1_idx` (`addedBy` ASC) ,
  INDEX `fk_voter_district1_idx` (`districtID` ASC) ,
  INDEX `fk_voter_precinct1_idx1` (`precinctID` ASC) )
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8;
